name: Cypress Tests

on:
  push:
    branches:
      - challenge-qa
  pull_request:
    branches:
      - challenge-qa

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Usar Ubuntu 22.04 para evitar problemas com o Ubuntu 24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use a versão do Node.js que seu projeto requer

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run